# Generated by Django 4.2.6 on 2023-11-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employes',
            new_name='Employees',
        ),
    ]
