# Generated by Django 4.2.6 on 2023-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_employes_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
